# Generated by Django 5.1.4 on 2025-01-13 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='fitness_goals',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='group_activity_type',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='group_location',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='group_schedule',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='workout_preferences',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
