# Generated by Django 5.1.4 on 2025-01-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_activity_fitnessgroup_workoutbuddyprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dashboard_preferences',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
