# Generated by Django 5.1.4 on 2025-01-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_fitnessgroup_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutbuddyprofile',
            name='fitness_goals',
            field=models.JSONField(),
        ),
    ]
