# Generated by Django 5.1.4 on 2025-01-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_workoutbuddyprofile_fitness_goals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutbuddyprofile',
            name='workout_preferences',
            field=models.JSONField(),
        ),
    ]
