# Generated by Django 5.1.4 on 2025-01-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_workoutbuddyprofile_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutbuddyprofile',
            name='availability',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workoutbuddyprofile',
            name='fitness_goals',
            field=models.CharField(blank=True, choices=[('muscle_gain', 'Muscle Gain'), ('weight_gain', 'Weight Gain'), ('weight_loss', 'Weight Loss'), ('improve_stamina', 'Improve Stamina'), ('improve_strength', 'Improve Strength'), ('calm_mind', 'Calm Mind')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='workoutbuddyprofile',
            name='workout_preferences',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
