# Generated by Django 5.1.4 on 2025-01-22 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_workoutbuddyprofile_availability_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitnessgroup',
            name='description',
        ),
    ]
