# Generated by Django 5.1.4 on 2025-01-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_fitnessgroup_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutbuddyprofile',
            name='fitness_goals',
            field=models.CharField(blank=True, choices=[('muscle_gain', 'Muscle Gain'), ('weight_gain', 'Weight Gain'), ('weight_loss', 'Weight Loss'), ('improve_stamina', 'Improve Stamina'), ('improve_strength', 'Improve Strength'), ('calm_mind', 'Calm Mind')], max_length=50, null=True, unique=True),
        ),
    ]
