# Generated by Django 5.1.4 on 2025-01-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_workoutbuddyprofile_fitness_goals'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='workoutbuddyprofile',
            name='experience_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workoutbuddyprofile',
            name='preferred_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='workoutbuddyprofile',
            name='fitness_goals',
        ),
        migrations.AddField(
            model_name='workoutbuddyprofile',
            name='fitness_goals',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='users.fitnessgoal'),
        ),
    ]
