# Generated by Django 5.1.4 on 2025-01-22 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_fitnessgoal_workoutbuddyprofile_experience_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutbuddyprofile',
            name='fitness_goals',
        ),
        migrations.DeleteModel(
            name='FitnessGoal',
        ),
    ]
